In [ ]:
import pandas as pd
import numpy as np

# load first dataset

In [50]:
df1= pd.read_csv('used_cars_data.csv')
df1.head(5)

/var/folders/07/fzlz2lpn2dzf5c57zk4bnd8c0000gn/T/ipykernel_14054/370569934.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df1= pd.read_csv('used_cars_data.csv')

,vin,back_legroom,bed,bed_height,bed_length,body_type,cabin,city,city_fuel_economy,combine_fuel_economy,...,transmission,transmission_display,trimId,trim_name,vehicle_damage_category,wheel_system,wheel_system_display,wheelbase,width,year
0,ZACNJABB5KPJ92081,35.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,Bayamon,NaN,NaN,...,A,9-Speed Automatic Overdrive,t83804,Latitude FWD,NaN,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019
1,SALCJ2FX1LH858117,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020
2,JF1VA2M67G9829723,35.4 in,NaN,NaN,NaN,Sedan,NaN,Guaynabo,17.0,NaN,...,M,6-Speed Manual,t58994,Base,NaN,AWD,All-Wheel Drive,104.3 in,78.9 in,2016
3,SALRR2RV0L2433391,37.6 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,8-Speed Automatic Overdrive,t86074,V6 HSE AWD,NaN,AWD,All-Wheel Drive,115 in,87.4 in,2020
4,SALCJ2FXXLH862327,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020

# Drop columns taht are not needed( selecting the columns based on kaggle stats on the display of data)

In [51]:
df1 = df1.drop(columns=['bed', 'bed_height','bed_length','combine_fuel_economy','engine_type','fleet','is_certified','is_cpo','is_oemcpo','main_picture_url','theft_title','trimId','vehicle_damage_category'])

In [56]:
print(df1.columns)

Index(['vin', 'back_legroom', 'body_type', 'cabin', 'city',
       'city_fuel_economy', 'daysonmarket', 'dealer_zip', 'description',
       'engine_cylinders', 'engine_displacement', 'exterior_color',
       'frame_damaged', 'franchise_dealer', 'franchise_make', 'front_legroom',
       'fuel_tank_volume', 'fuel_type', 'has_accidents', 'height',
       'highway_fuel_economy', 'horsepower', 'interior_color', 'isCab',
       'is_new', 'latitude', 'length', 'listed_date', 'listing_color',
       'listing_id', 'longitude', 'major_options', 'make_name',
       'maximum_seating', 'mileage', 'model_name', 'owner_count', 'power',
       'price', 'salvage', 'savings_amount', 'seller_rating', 'sp_id',
       'sp_name', 'torque', 'transmission', 'transmission_display',
       'trim_name', 'wheel_system', 'wheel_system_display', 'wheelbase',
       'width', 'year'],
      dtype='object')

# load second dataset

In [57]:
df2= pd.read_csv('vehicles.csv')
df2.head(5)

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [58]:
print(df2.columns)

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='object')

# Renaming the columns in the second dataset to match the column names of first dataset

In [60]:
df2.rename(columns={'region': 'city', 'manufacturer': 'make_name','model': 'model_name','fuel': 'fuel_type','VIN': 'vin','drive':'wheel_system_display','type':'body_type','paint_color':'exterior_color','lat':'latitude','long':'longitude','posting_date':'listed_date'}, inplace=True)
print(df2.columns)

Index(['id', 'url', 'city', 'region_url', 'price', 'year', 'make_name',
       'model_name', 'condition', 'cylinders', 'fuel_type', 'odometer',
       'title_status', 'transmission', 'vin', 'wheel_system_display', 'size',
       'body_type', 'exterior_color', 'image_url', 'description', 'county',
       'state', 'latitude', 'longitude', 'listed_date'],
      dtype='object')

# Dropping the unwanted columns in second dataset

In [61]:
df2 = df2.drop(columns=['id', 'url', 'region_url','condition', 'cylinders', 'odometer','title_status', 'size','county','state'])
len(df2.columns)
print(df2.columns)

Index(['city', 'price', 'year', 'make_name', 'model_name', 'fuel_type',
       'transmission', 'vin', 'wheel_system_display', 'body_type',
       'exterior_color', 'image_url', 'description', 'latitude', 'longitude',
       'listed_date'],
      dtype='object')

# Performing data standardization before merging both dataset

In [62]:
df2.loc[:,"wheel_system_display"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
426875    fwd
426876    fwd
426877    NaN
426878    fwd
426879    rwd
Name: wheel_system_display, Length: 426880, dtype: object

In [63]:
df2['wheel_system_display'] = df2['wheel_system_display'].str.upper()
df2.loc[:,"wheel_system_display"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
426875    FWD
426876    FWD
426877    NaN
426878    FWD
426879    RWD
Name: wheel_system_display, Length: 426880, dtype: object

# Merging dataset

In [64]:
list = ["city", "price", "year", "make_name","model_name","fuel_type","transmission","vin","wheel_system_display","body_type","exterior_color","description","latitude","longitude","listed_date"]
df_combine = df1.merge(df2,
                   on = list, 
                   how = 'outer')
df_combine.head(5)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py:1207: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  warnings.warn(

,vin,back_legroom,body_type,cabin,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,...,torque,transmission,transmission_display,trim_name,wheel_system,wheel_system_display,wheelbase,width,year,image_url
0,ZACNJABB5KPJ92081,35.1 in,SUV / Crossover,NaN,Bayamon,NaN,522.0,960,[!@@Additional Info@@!]Engine: 2.4L I4 ZERO EV...,I4,...,"200 lb-ft @ 1,750 RPM",A,9-Speed Automatic Overdrive,Latitude FWD,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019.0,NaN
1,SALCJ2FX1LH858117,38.1 in,SUV / Crossover,NaN,San Juan,NaN,207.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,...,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0,NaN
2,JF1VA2M67G9829723,35.4 in,Sedan,NaN,Guaynabo,17.0,1233.0,969,NaN,H4,...,"290 lb-ft @ 4,000 RPM",M,6-Speed Manual,Base,AWD,All-Wheel Drive,104.3 in,78.9 in,2016.0,NaN
3,SALRR2RV0L2433391,37.6 in,SUV / Crossover,NaN,San Juan,NaN,196.0,922,"[!@@Additional Info@@!]Fog Lights,7 Seat Packa...",V6,...,"332 lb-ft @ 3,500 RPM",A,8-Speed Automatic Overdrive,V6 HSE AWD,AWD,All-Wheel Drive,115 in,87.4 in,2020.0,NaN
4,SALCJ2FXXLH862327,38.1 in,SUV / Crossover,NaN,San Juan,NaN,137.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,...,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0,NaN

# Checking for percent of missing values by columns and dropping irrelevant coulmns

In [66]:
total_rows = len(df_combine)
missing_values = df_combine.isnull().sum()
percentage_missing = (missing_values / total_rows) * 100

# Now, 'percentage_missing' will contain the percentage of missing values for each column
print(percentage_missing)

vin                      4.699322
back_legroom            17.104251
body_type                3.104858
cabin                   98.146061
city                     0.000000
city_fuel_economy       26.792718
daysonmarket            12.456667
dealer_zip              12.456667
description              2.275250
engine_cylinders        15.391693
engine_displacement     17.487015
exterior_color           3.800176
frame_damaged           54.085739
franchise_dealer        12.456667
franchise_make          29.166569
front_legroom           17.104251
fuel_tank_volume        17.104251
fuel_type                2.501868
has_accidents           54.085739
height                  17.104251
highway_fuel_economy    26.792718
horsepower              17.487015
interior_color          12.461481
isCab                   54.085739
is_new                  12.456667
latitude                 0.191105
length                  17.104251
listed_date              0.001984
listing_color           12.456667
listing_id              12.456667
longitude                0.191105
major_options           18.294212
make_name                0.514923
maximum_seating         17.104251
mileage                 16.669984
model_name               0.153987
owner_count             56.724201
power                   26.505025
price                    0.000000
salvage                 54.085739
savings_amount          12.456667
seller_rating           13.649341
sp_id                   12.459468
sp_name                 12.456667
torque                  27.566240
transmission             1.947551
transmission_display    14.329631
trim_name               15.850210
wheel_system            16.738412
wheel_system_display     8.091785
wheelbase               17.104251
width                   17.104251
year                     0.035163
image_url               87.545318
dtype: float64

In [70]:
df_combine = df_combine.drop(columns=['cabin', 'image_url'])

# Vin number is primary key and missing values need to be dorpped and incorrect vin numbers need to be dropped aswell

In [71]:
df_combine = df_combine.dropna(axis=0, subset=['vin'])
df_combine.head(5)

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,sp_name,torque,transmission,transmission_display,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
0,ZACNJABB5KPJ92081,35.1 in,SUV / Crossover,Bayamon,NaN,522.0,960,[!@@Additional Info@@!]Engine: 2.4L I4 ZERO EV...,I4,1300.0,...,Flagship Chrysler,"200 lb-ft @ 1,750 RPM",A,9-Speed Automatic Overdrive,Latitude FWD,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019.0
1,SALCJ2FX1LH858117,38.1 in,SUV / Crossover,San Juan,NaN,207.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,Land Rover San Juan,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0
2,JF1VA2M67G9829723,35.4 in,Sedan,Guaynabo,17.0,1233.0,969,NaN,H4,2500.0,...,FIAT de San Juan,"290 lb-ft @ 4,000 RPM",M,6-Speed Manual,Base,AWD,All-Wheel Drive,104.3 in,78.9 in,2016.0
3,SALRR2RV0L2433391,37.6 in,SUV / Crossover,San Juan,NaN,196.0,922,"[!@@Additional Info@@!]Fog Lights,7 Seat Packa...",V6,3000.0,...,Land Rover San Juan,"332 lb-ft @ 3,500 RPM",A,8-Speed Automatic Overdrive,V6 HSE AWD,AWD,All-Wheel Drive,115 in,87.4 in,2020.0
4,SALCJ2FXXLH862327,38.1 in,SUV / Crossover,San Juan,NaN,137.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,Land Rover San Juan,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0

In [72]:
df_combine = df_combine[df_combine['vin'].str.contains('[A-Za-z]')]

print(df_combine)

                       vin back_legroom        body_type      city  \
0        ZACNJABB5KPJ92081      35.1 in  SUV / Crossover   Bayamon
1        SALCJ2FX1LH858117      38.1 in  SUV / Crossover  San Juan
2        JF1VA2M67G9829723      35.4 in            Sedan  Guaynabo
3        SALRR2RV0L2433391      37.6 in  SUV / Crossover  San Juan
4        SALCJ2FXXLH862327      38.1 in  SUV / Crossover  San Juan
...                    ...          ...              ...       ...
3426915  1N4AA6AV6KC367801          NaN            sedan   wyoming
3426916  7JR102FKXLG042696          NaN            sedan   wyoming
3426917  1GYFZFR46LF088296          NaN        hatchback   wyoming
3426918  58ABK1GG4JU103853          NaN            sedan   wyoming
3426919  WBA4J1C58KBM14708          NaN            coupe   wyoming

         city_fuel_economy  daysonmarket dealer_zip  \
0                      NaN         522.0        960
1                      NaN         207.0        922
2                     17.0        1233.0        969
3                      NaN         196.0        922
4                      NaN         137.0        922
...                    ...           ...        ...
3426915                NaN           NaN        NaN
3426916                NaN           NaN        NaN
3426917                NaN           NaN        NaN
3426918                NaN           NaN        NaN
3426919                NaN           NaN        NaN

                                               description engine_cylinders  \
0        [!@@Additional Info@@!]Engine: 2.4L I4 ZERO EV...               I4
1        [!@@Additional Info@@!]Keyless Entry,Ebony Mor...               I4
2                                                      NaN               H4
3        [!@@Additional Info@@!]Fog Lights,7 Seat Packa...               V6
4        [!@@Additional Info@@!]Keyless Entry,Ebony Mor...               I4
...                                                    ...              ...
3426915  Carvana is the safer way to buy a car During t...              NaN
3426916  Carvana is the safer way to buy a car During t...              NaN
3426917  Carvana is the safer way to buy a car During t...              NaN
3426918  Carvana is the safer way to buy a car During t...              NaN
3426919  Carvana is the safer way to buy a car During t...              NaN

         engine_displacement  ...              sp_name                 torque  \
0                     1300.0  ...    Flagship Chrysler  200 lb-ft @ 1,750 RPM
1                     2000.0  ...  Land Rover San Juan  269 lb-ft @ 1,400 RPM
2                     2500.0  ...     FIAT de San Juan  290 lb-ft @ 4,000 RPM
3                     3000.0  ...  Land Rover San Juan  332 lb-ft @ 3,500 RPM
4                     2000.0  ...  Land Rover San Juan  269 lb-ft @ 1,400 RPM
...                      ...  ...                  ...                    ...
3426915                  NaN  ...                  NaN                    NaN
3426916                  NaN  ...                  NaN                    NaN
3426917                  NaN  ...                  NaN                    NaN
3426918                  NaN  ...                  NaN                    NaN
3426919                  NaN  ...                  NaN                    NaN

        transmission         transmission_display     trim_name wheel_system  \
0                  A  9-Speed Automatic Overdrive  Latitude FWD          FWD
1                  A  9-Speed Automatic Overdrive         S AWD          AWD
2                  M               6-Speed Manual          Base          AWD
3                  A  8-Speed Automatic Overdrive    V6 HSE AWD          AWD
4                  A  9-Speed Automatic Overdrive         S AWD          AWD
...              ...                          ...           ...          ...
3426915        other                          NaN           NaN          NaN
3426916        other                          NaN           NaN          NaN
3426917        other                          NaN           NaN          NaN
3426918        other                          NaN           NaN          NaN
3426919        other                          NaN           NaN          NaN

        wheel_system_display wheelbase    width    year
0          Front-Wheel Drive  101.2 in  79.6 in  2019.0
1            All-Wheel Drive  107.9 in  85.6 in  2020.0
2            All-Wheel Drive  104.3 in  78.9 in  2016.0
3            All-Wheel Drive    115 in  87.4 in  2020.0
4            All-Wheel Drive  107.9 in  85.6 in  2020.0
...                      ...       ...      ...     ...
3426915                  FWD       NaN      NaN  2019.0
3426916                  FWD       NaN      NaN  2020.0
3426917                  NaN       NaN      NaN  2020.0
3426918                  FWD       NaN      NaN  2018.0
3426919                  RWD       NaN      NaN  2019.0

[3264778 rows x 52 columns]

In [73]:
dups_vin = df_combine.pivot_table(columns=['vin'], aggfunc='size')
dups_vin = dups_vin[dups_vin > 1]

print(dups_vin)

vin
0000000RN47028886    3
0000000T05H107426    2
0000000V264204442    2
0000004Y83Z146570    2
000000ECR33107314    2
                    ..
ZN661XUL7HX239289    3
ZN661XUS7HX248033    2
ZN661YUA4LX344692    2
ZN661YUS0HX263351    2
ZPBUA1ZL1KLA02237    2
Length: 42729, dtype: int64

In [74]:
df_combine = df_combine.drop_duplicates(subset=['vin'])
df_combine['vin'].is_unique

True

# Creating 3 more columns as primary key to split the dataset into a STAR schema model

In [77]:
start_row = 1
width = 7
prefix1 = 'LOC'
prefix2 = 'DEA'
prefix3 = 'LIS'

df_combine['Location_ID'] = prefix1 + (df_combine.index + start_row).map(str).str.zfill(width)
df_combine['Dealer_ID'] = prefix2 + (df_combine.index + start_row).map(str).str.zfill(width)
df_combine['listing_ID'] = prefix3 + (df_combine.index + start_row).map(str).str.zfill(width)

In [78]:
df_combine.head(5)

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,transmission_display,trim_name,wheel_system,wheel_system_display,wheelbase,width,year,Location_ID,Dealer_ID,listing_ID
0,ZACNJABB5KPJ92081,35.1 in,SUV / Crossover,Bayamon,NaN,522.0,960,[!@@Additional Info@@!]Engine: 2.4L I4 ZERO EV...,I4,1300.0,...,9-Speed Automatic Overdrive,Latitude FWD,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019.0,LOC0000001,DEA0000001,LIS0000001
1,SALCJ2FX1LH858117,38.1 in,SUV / Crossover,San Juan,NaN,207.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0,LOC0000002,DEA0000002,LIS0000002
2,JF1VA2M67G9829723,35.4 in,Sedan,Guaynabo,17.0,1233.0,969,NaN,H4,2500.0,...,6-Speed Manual,Base,AWD,All-Wheel Drive,104.3 in,78.9 in,2016.0,LOC0000003,DEA0000003,LIS0000003
3,SALRR2RV0L2433391,37.6 in,SUV / Crossover,San Juan,NaN,196.0,922,"[!@@Additional Info@@!]Fog Lights,7 Seat Packa...",V6,3000.0,...,8-Speed Automatic Overdrive,V6 HSE AWD,AWD,All-Wheel Drive,115 in,87.4 in,2020.0,LOC0000004,DEA0000004,LIS0000004
4,SALCJ2FXXLH862327,38.1 in,SUV / Crossover,San Juan,NaN,137.0,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,9-Speed Automatic Overdrive,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020.0,LOC0000005,DEA0000005,LIS0000005

In [ ]:
df_combine.to_csv('used_car_dataset.csv', index=False)